server:
  port: 8067
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes: 
      - id: PATIENT-SERVICE
        uri:
           lb://PATIENT-SERVICE
        predicates:
        - Path=/patients/**
        
      - id: DOCTOR-SERVICE
        uri:
           lb://DOCTOR-SERVICE
        predicates:
        - Path=/doctors/**
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

        
   
